### ISSUE TITLE
Mouseover color resets original tract color to default

### ISSUE THREAD

**Issue by ladyson** [meemking/CrimeScape#26]
After mousing over a tract so it is highlighted blue, the tract defaults back to yellow instead of the original red/green color that corresponds to regular risk. @lw334 any easy way to fix this?

![screen shot 2016-01-20 at 7 29 49 pm](https://cloud.githubusercontent.com/assets/1771715/12468787/342d3cf0-bfac-11e5-91f5-8f235690c060.png)

**Comment by lw334** [comment]
Just fixed it. See the latest change.

**Comment by ladyson** [comment]
Thanks Lingwei!
